name: Build liboqs on Linux

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version of checkout

    - name: Set up CMake
      uses: cmake/setup-cmake@v3  # Correct action for setting up CMake
      with:
        cmake-version: '3.21'  # Specify the CMake version, adjust as necessary

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libssl-dev  # Add any dependencies that are required for your project

    - name: Build liboqs
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Upload Build Artifacts
      if: success()  # Only upload artifacts if the build was successful
      uses: actions/upload-artifact@v4  # Use the latest version of upload-artifact
      with:
        name: liboqs-build
        path: |
          build/liboqs.so
          build/liboqs.dll

    - name: Run Tests
      if: success()
      run: |
        cd build
        ninja test
